### ISSUE TITLE
Mtree not working with Blender 3.1.0 ??

### ISSUE THREAD

**Issue by theShiZa** [MaximeHerpin/modular_tree#343]
Hi.

I've tried every Mtree version I could find but it's just not working with Blender 3.1.0.

It seems to install fine but in Blender Preferences/AddOns when I try to enable Mtree it won't let me tick the checkbox to enable it. Says the following message ;;;

Traceback (most recent call last):
  File "C:\Program Files\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ASH\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree-blender_31\__init__.py", line 16, in <module>
    from . import python_classes
  File "C:\Users\ASH\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree-blender_31\python_classes\__init__.py", line 2, in <module>
    from . import nodes
  File "C:\Users\ASH\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree-blender_31\python_classes\nodes\__init__.py", line 6, in <module>
    from . import sockets
  File "C:\Users\ASH\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree-blender_31\python_classes\nodes\sockets\__init__.py", line 6, in <module>
    from .property_socket import MtreePropertySocket
  File "C:\Users\ASH\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree-blender_31\python_classes\nodes\sockets\property_socket.py", line 3, in <module>
    from ....m_tree import ConstantProperty, RandomProperty, PropertyWrapper
ImportError: cannot import name 'ConstantProperty' from 'modular_tree-blender_31.m_tree' (unknown location)

Really love this addon, has anyone got it working with Blender 3.1.0 so far??

**Comment by theShiZa** [comment]
I tried Mtree versions 4_0_2 & 31 & Rework but they don't work with Blender 3.1.0, but then I went back to the Mtree 28 version & it's the only one that at least lets me install & enable Mtree. It's working but I haven't tested all the Mtree options to see if everything works like before yet.

**Comment by zookini** [comment]
I have a similar problem with Blender 3.1.0 on Windows 10. MTree seems to install fine, but when I try to enable it nothing happens. I see the following on the console:
```
Read prefs: C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
addon not loaded: 'modular_tree'
cause: cannot import name 'm_tree' from partially initialized module 'modular_tree' (most likely due to a circular import) (C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\modular_tree\__init__.py)
addon_utils.disable: modular_tree not disabled
addon_utils.disable: modular_tree not disabled
Modules Installed (modular_tree) from 'C:\\Users\\me\\Downloads\\modular_tree_4_0_2_windows.zip' into 'C:\\Users\\me\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
addon not loaded: 'modular_tree'
```

**Comment by DeltaCDesigns** [comment]
I don't believe they do. The base install worked, but preset load functionality doesn't work, give error code attached as .png:
![Screenshot 2022-03-26 123737](https://user-images.githubusercontent.com/99465450/160248942-26b3d9fe-2174-4412-ad86-34e8c70f7d8f.png)
.

Additionally, when manually adding nodes, no node functionality is present in node stack:

![Screenshot 2022-03-26 124103](https://user-images.githubusercontent.com/99465450/160249097-19689fa0-7be6-44c5-ac01-25ded4560ef6.png)

**Comment by timothyj6767** [comment]
same error

**Comment by jetley** [comment]
here with blender 3.1.2. Can't enable add-on neither.

**Comment by mysteryletsplay** [comment]
Hello I have the same Problem with Blender 3.1.2 did somebody fix the problem or knows how to work around the problem?

**Comment by javismiles** [comment]
same problem here, anybody found a solution?

**Comment by mysteryletsplay** [comment]
> same problem here, anybody found a solution?

No sry didnt find solution

**Comment by winfriedeirfniw** [comment]
Same here - Installs ok but can't enable in 3.3

**Comment by ShengzhiWu** [comment]
Same error.

**Comment by ShengzhiWu** [comment]
A developer has solved the problem. I tried it in blender 3.3 and it works! Go to https://github.com/steven-ray/modular_tree/releases and download an appropriate built release.

**Comment by winfriedeirfniw** [comment]
Thank you - this new 4.0.2.1a works properly!

**Comment by SantoCaldarella** [comment]
Hi, the new version works but... it's quite different than before... how i can personalize the twigs? i have no node. it's strange
