### ISSUE TITLE
mTree not working on Blender 3.1.2

### ISSUE THREAD

**Issue by javismiles** [MaximeHerpin/modular_tree#355]
I have tried other alternatives provided by others in other issues but no luck,
anybody has any solution to make the addOn work on 3.1.2? (which I need for my project)
thank you very much, my system is:
Windows 10, Blender 3.1.2

**Comment by ecker00** [comment]
Just to add some more details to this (Blender 3.2).

When enabling the add-on the `Window → Toggle System Console`  shows:
```sh
addon not loaded: 'modular_tree'
cause: cannot import name 'm_tree' from partially initialized module 'modular_tree' (most likely due to a circular import) (~\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree\__init__.py) 
```

### **Edit:**
See solution in issue https://github.com/MaximeHerpin/modular_tree/issues/356
