### ISSUE TITLE
FIX-Not working on blender 2.93

### ISSUE THREAD

**Issue by kahpas** [MaximeHerpin/modular_tree#270]
--------
**edit:**
> Hi, see here:
> https://blenderartists.org/t/modular-tree/674043/923

This fix worked for me. Thanks YAFU!

----------
I am using mtree (28  branch) on blender 2.93. I am using the blender_28 branch on Ubuntu 20.04.
When I open a mtree editor and click load preset I get an error:
```
Python: Traceback (most recent call last):
  File "/home/kahpas/.config/blender/2.93/scripts/addons/modular_tree-blender_28/nodes/node_tree.py", line 216, in draw
    op.node_group_name = tree.name #set node group name as curent node tree name
AttributeError: 'MTREE_OT_save_preset' object has no attribute 'node_group_name'

location: <unknown location>:-1
```

I can see all of the nodes but they are empty (some have in and output connectors)
The "Trunk Node" has an "update strokes" button which produces the following error:
```
Python: Traceback (most recent call last):
  File "/home/kahpas/.config/blender/2.93/scripts/addons/modular_tree-blender_28/nodes/trunk_node.py", line 35, in draw_buttons
    op.node_group_name = self.id_data.name # set name of node group to operator
AttributeError: 'MTREE_OT_update_gp_strokes' object has no attribute 'node_group_name'

location: <unknown location>:-1

```
The "Twig Node" has an execute button which produces the following error:

```
Python: Traceback (most recent call last):
  File "/home/kahpas/.config/blender/2.93/scripts/addons/modular_tree-blender_28/nodes/trunk_node.py", line 35, in draw_buttons
    op.node_group_name = self.id_data.name # set name of node group to operator
AttributeError: 'MTREE_OT_update_gp_strokes' object has no attribute 'node_group_name'

location: <unknown location>:-1
```
Is there a fix for these problems or do I just have to wait for an mtree update (I tried the master an the 3.0.0 branch but they produce the upgrade to 2.8x error)

**Comment by rhysday** [comment]
Is MTree still being developed? haven't seen any updates in awhile.

**Comment by devoh747** [comment]
I had read a while back that the dev went on to work on Unity or was it Unreal.. but has not come back.  Honestly, someone should fork this and keep it alive.

**Comment by topologie11** [comment]
hello , same problem .  2.93 is out and add on  doesn't work any more  . work well with 2.92 but not with the new 2.93 version .

**Comment by YAFU** [comment]
Hi, see here:
https://blenderartists.org/t/modular-tree/674043/923

**Comment by Grey-Junior** [comment]
> Hi, see here:
> https://blenderartists.org/t/modular-tree/674043/923

Thanks, It worked!

**Comment by BriAri1** [comment]
> 
> 
> Hi, see here:
> https://blenderartists.org/t/modular-tree/674043/923

Thanks a lot!

**Comment by topologie11** [comment]
hello 

> Hi, see here:
> https://blenderartists.org/t/modular-tree/674043/923

hello , thank a lot , work very well . 

to see what line have been modified  , i ve used in console 
 
 diff -r modular_tree-blender_28/ modular_tree-blender_293/ >> diff.txt

main change are   
   i) some  "="  =>   ":" 
  ii ) time.clock()  => time.process_time()
 iii)  translate some english text to spanish text  ( this can be modified back to english without problem )   

i ve started to learn python but i am far away to be able to do the same thing to correct this type of add on . lot of work again 

 thank a lot for the fix of this great add on 
[diff.txt](https://github.com/MaximeHerpin/modular_tree/files/6680441/diff.txt)

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
