### ISSUE TITLE
FIXED-Addon doesn't work on Blender 2.93LTS & macOS 10.13.6

### ISSUE THREAD

**Issue by Oxervision** [MaximeHerpin/modular_tree#269]
Hi, when I try to create a modular tree on Blender 2.93LTS it appears this error message:

```
Error: Python: Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/SCRIPTS/addons/Modular tree/nodes/tree_parameters_node.py", line 421, in execute
    node.execute()
  File "/Users/User/Library/Application Support/Blender/SCRIPTS/addons/Modular tree/nodes/tree_parameters_node.py", line 75, in execute
    t0 = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

Someone can help to fix the issue?

Thanks in advance!!

**Blender 2.93 LTS & macOS 10.13.6**

**Comment by Oxervision** [comment]
Searching on internet I found the solution to fix the issue, I changed **time.clock()** to **time.process_time()** in **tree_parameters_node.py** file, the addon works fine on 2.8 to 2.93LTS now.

[tree_parameters_node-fixed(for 2.8-2.93TTS).zip](https://github.com/MaximeHerpin/modular_tree/files/6616332/tree_parameters_node-fixed.for.2.8-2.93TTS.zip)

• Instructions:

Place the file above into Modular tree folder --> **Modular tree/nodes/tree_parameters_node.py**

**Comment by BriAri1** [comment]
I seem to be getting a different error, got any ideas? 

I am on blender 2.93 
 ```
Python: Traceback (most recent call last):
  File "C:\Users\BlueBishop\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\nodes\node_tree.py", line 216, in draw
    op.node_group_name = tree.name #set node group name as current node tree name
AttributeError: 'MTREE_OT_save_preset' object has no attribute 'node_group_name'

location: <unknown location>:-1
```
line 216

`op.node_group_name = tree.name #set node group name as current node tree name`

Thanks.

**Comment by BriAri1** [comment]
No it was major coding issue someone else resolved thanks though.

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
