### ISSUE TITLE
Problem. (Mtree 3.1.0 - Blender 2.93.2) 

### ISSUE THREAD

**Issue by P3nco** [MaximeHerpin/modular_tree#294]
This problem pops up as soon as i click "load preset" in mtree node tree. 
----------------------------------------------------------
Python: Traceback (most recent call last):
  File "C:\Users\lutri\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\nodes\node_tree.py", line 216, in draw
    op.node_group_name = tree.name #set node group name as curent node tree name
AttributeError: 'MTREE_OT_save_preset' object has no attribute 'node_group_name'

location: <unknown location>:-1

**Comment by Minazak1** [comment]
I also have this problem and the plugin does not work

**Comment by schipiga** [comment]
@Minazak1 , @P3nco , you can download working version in https://github.com/MaximeHerpin/modular_tree/pull/289

**Comment by RinkuMeena** [comment]
plug in working on blender 2.93 but blender crashed after 5 minute using this add-on

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
